name: Rust Lint

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory containing Cargo.toml"
        type: string
        default: "."

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: drGrove/shared-workflows/actions/cargo-fmt@main
        with:
          working-directory: ${{ inputs.working-directory }}

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: drGrove/shared-workflows/actions/cargo-clippy@main
        with:
          working-directory: ${{ inputs.working-directory }}
