name: Rust Test

on:
  workflow_call:

jobs:
  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: drGrove/shared-workflows/actions/cargo-test@main
