name: Rust Test

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory containing Cargo.toml"
        type: string
        default: "."

jobs:
  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: drGrove/shared-workflows/actions/cargo-test@main
        with:
          working-directory: ${{ inputs.working-directory }}
